### ISSUE TITLE
Clean all npm script

### ISSUE THREAD

**Issue by kennarddh** [kennarddh/express-boilerplate#348]
**Is your feature request related to a problem? Please describe.**
Need to run all clean script to clean all temporary data.

**Describe the solution you'd like**
A new script that will run all clean script `clean:all`.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by gokullan** [comment]
Hi, there. I'm interested in contributing. So basically I would need to add a line for  `clean:all` in `package.json` and this should invoke all clean-related code (build, dist, logs, coverage), correct? Can this be assigned to me?

**Comment by kennarddh** [comment]
Yes

**Comment by kennarddh** [comment]
Closed by #350
